# Source: cluster-api-aws/templates/aws-cluster.yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AWSCluster
metadata:
  name: 3fcc4656-6512-474f-bb29-8143f2df1865
  namespace: 3fcc4656-6512-474f-bb29-8143f2df1865
spec:
  region: ap-northeast-2
  sshKeyName: tks-seoul
  bastion:
    enabled: true
    instanceType: t3.micro
    disableIngressRules: false
    allowedCIDRBlocks:
      - 127.0.0.1/32
