# Source: cluster-api-aws/templates/job-check.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: 3fcc4656-6512-474f-bb29-8143f2df1865-capi-aws-check
  namespace: 3fcc4656-6512-474f-bb29-8143f2df1865
spec:
  template:
    metadata:
      name: 3fcc4656-6512-474f-bb29-8143f2df1865-capi-aws
    spec:
      serviceAccountName: 3fcc4656-6512-474f-bb29-8143f2df1865-capi-aws
      containers:
      - name: wait-for-ready
        image: "ghcr.io/openinfradev/python_kubectl_argo:v1.1.0"
        imagePullPolicy: IfNotPresent
        command:
        - timeout 
        - 5m
        - /wait_for_kubeconfig.sh  
        - 3fcc4656-6512-474f-bb29-8143f2df1865
        - 3fcc4656-6512-474f-bb29-8143f2df1865
        volumeMounts:
        - name: vol
          subPath: wait_for_kubeconfig.sh
          mountPath: /wait_for_kubeconfig.sh
      volumes:
      - name: vol
        configMap:
          name: 3fcc4656-6512-474f-bb29-8143f2df1865-capi-aws
          defaultMode: 0555
      restartPolicy: OnFailure
